name: carwash
description: EzyWash is a car service app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.0.1+2

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
dev.flutter/flutter:
  version: ^3.13.6
  connectivity:
  cupertino_icons:
  date_format:
  flutter_staggered_grid_view:
  geocoding:
  geolocator:
  google_maps_flutter: ^2.0.6
  http:
  intl:
  liquid_progress_indicator:
  loading_overlay:
  mailer:
  permission_handler:
  shared_preferences:
  webview_flutter: ^3.0.0
  file: ^6.0.0-nullsafety.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.1

dependency_overrides:
  # Override path_provider to pick up fixes for FFI changes.
  path_provider: ^2.0.0-nullsafety.1

flutter:
  uses-material-design: true
  assets:
    - IMAGES/
